LANGUAGE = "spanish"
PRETRAINED_EMBEDDINGS_PATH = "~/aprendizajeProfundo/data/SBW-vectors-300-min5.txt.gz"
TEST_DATA_PATH = "~/aprendizajeProfundo/data/meli-challenge-2019/spanish.test.jsonl.gz"
TOKEN_TO_INDEX_PATH = "~/aprendizajeProfundo/data/meli-challenge-2019/spanish_token_to_index.json.gz"
TRAIN_DATA_PATH = "~/aprendizajeProfundo/data/meli-challenge-2019/spanish.train.jsonl.gz"
VALIDATION_DATA_PATH = "~/aprendizajeProfundo/data/meli-challenge-2019/spanish.validation.jsonl.gz"
